# Generated by Django 2.2.2 on 2019-06-29 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontoturistico',
            name='descricao',
            field=models.TextField(),
        ),
    ]
